import os
from datetime import datetime
from typing import Dict, Any
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
import logging

logger = logging.getLogger(__name__)

class ReportService:
    """Service for generating Markdown and PDF reports"""
    
    @staticmethod
    def generate_markdown(analysis_data: Dict[str, Any], job_id: str) -> str:
        """
        Generate Markdown report
        
        Args:
            analysis_data: Analysis results
            job_id: Job ID
            
        Returns:
            Absolute path to generated report
        """
        try:
            # Get absolute path to reports directory
            current_dir = os.path.dirname(os.path.abspath(__file__))
            reports_dir = os.path.abspath(os.path.join(current_dir, "../../../reports"))
            os.makedirs(reports_dir, exist_ok=True)
            
            # Generate filename
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"report_{job_id}_{timestamp}.md"
            filepath = os.path.abspath(os.path.join(reports_dir, filename))
            
            # Build markdown content
            md_content = ReportService._build_markdown_content(analysis_data, job_id)
            
            # Write to file
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(md_content)
            
            logger.info(f"✅ Markdown report generated: {filepath}")
            
            # Return absolute path
            return filepath
            
        except Exception as e:
            logger.error(f"❌ Failed to generate Markdown report: {e}")
            raise
    
    @staticmethod
    def _build_markdown_content(data: Dict[str, Any], job_id: str) -> str:
        """Build markdown report content"""
        # Data is already in dict format from modernization_engine
        summary = data.get("summary", {})
        issues = data.get("issues", [])
        analysis = data.get("analysis", {})
        metadata = data.get("metadata", {})
        
        md = f"""# Legacy Code Modernization Report

**Job ID:** `{job_id}`  
**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}  
**Model:** {metadata.get('model', 'N/A')}  
**Processing Time:** {metadata.get('processing_time', 0):.2f}s  
**Cost:** ${metadata.get('cost_estimate', 0):.6f}

---

## Executive Summary

- **Files Analyzed:** {summary.get('files_analyzed', 0)}
- **Total Lines:** {summary.get('total_lines', 0):,}
- **Languages Detected:** {', '.join(summary.get('languages_detected', []))}

### Issues Found

- **Total Issues:** {summary.get('total_issues', 0)}
- **Critical:** {summary.get('critical', 0)} 🔴
- **Warnings:** {summary.get('warnings', 0)} 🟡
- **Info:** {summary.get('info', 0)} 🔵

---

## Critical Issues

"""
        
        # Add critical issues
        critical_issues = [i for i in issues if i.get('severity') == 'critical']
        if critical_issues:
            for idx, issue in enumerate(critical_issues, 1):
                md += f"""
### {idx}. {issue.get('message', 'N/A')}

**Type:** {issue.get('type', 'N/A').title()}  
**File:** `{issue.get('file', 'N/A')}`  
**Line:** {issue.get('line', 'N/A')}

**Issue:**
```
{issue.get('code_snippet', 'No code snippet available')}
```

**Recommendation:**
{issue.get('suggestion', 'No suggestion available')}

**Fixed Code:**
```
{issue.get('fixed_code', 'No fix provided')}
```

---
"""
        else:
            md += "\n*No critical issues found.*\n\n"
        
        # Add warnings
        md += "\n## Warnings\n\n"
        warning_issues = [i for i in issues if i.get('severity') == 'warning']
        if warning_issues:
            for idx, issue in enumerate(warning_issues, 1):
                md += f"""
### {idx}. {issue.get('message', 'N/A')}

**File:** `{issue.get('file', 'N/A')}` (Line {issue.get('line', 'N/A')})  
**Suggestion:** {issue.get('suggestion', 'No suggestion')}

---
"""
        else:
            md += "\n*No warnings found.*\n\n"
        
        # Add recommendations
        recommendations = analysis.get('recommendations', [])
        if recommendations:
            md += "\n## General Recommendations\n\n"
            for idx, rec in enumerate(recommendations, 1):
                md += f"{idx}. {rec}\n"
        
        # Add footer
        md += f"""

---

## Metadata

- **Cached Result:** {'Yes' if metadata.get('cached') else 'No'}
- **Tokens Used:** {metadata.get('tokens_used', 0):,}
- **Model Provider:** {metadata.get('model', 'N/A').split('-')[0].title()}

---

*Generated by Legacy Code Modernization Assistant*
"""
        
        return md
    
    @staticmethod
    def generate_pdf(analysis_data: Dict[str, Any], job_id: str) -> str:
        """
        Generate PDF report
        
        Args:
            analysis_data: Analysis results
            job_id: Job ID
            
        Returns:
            Path to generated PDF
        """
        try:
            # Create reports directory
            reports_dir = os.path.join(os.path.dirname(__file__), "../../../reports")
            os.makedirs(reports_dir, exist_ok=True)
            
            # Generate filename
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"report_{job_id}_{timestamp}.pdf"
            filepath = os.path.join(reports_dir, filename)
            
            # Create PDF
            doc = SimpleDocTemplate(filepath, pagesize=letter)
            styles = getSampleStyleSheet()
            story = []
            
            # Data is already in dict format
            metadata = analysis_data.get('metadata', {})
            summary = analysis_data.get('summary', {})
            
            # Title
            title_style = ParagraphStyle(
                'CustomTitle',
                parent=styles['Heading1'],
                fontSize=24,
                textColor='#333333',
                spaceAfter=30,
            )
            story.append(Paragraph("Legacy Code Modernization Report", title_style))
            story.append(Spacer(1, 0.2 * inch))
            
            # Metadata
            meta_text = f"""
            <b>Job ID:</b> {job_id}<br/>
            <b>Generated:</b> {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}<br/>
            <b>Files Analyzed:</b> {summary.get('files_analyzed', 0)}<br/>
            <b>Total Issues:</b> {summary.get('total_issues', 0)}<br/>
            <b>Cost:</b> ${metadata.get('cost_estimate', 0):.6f}
            """
            story.append(Paragraph(meta_text, styles['Normal']))
            story.append(Spacer(1, 0.3 * inch))
            
            # Issues summary
            story.append(Paragraph("Issues Summary", styles['Heading2']))
            issues_summary = f"""
            <b>Critical:</b> {summary.get('critical', 0)}<br/>
            <b>Warnings:</b> {summary.get('warnings', 0)}<br/>
            <b>Info:</b> {summary.get('info', 0)}
            """
            story.append(Paragraph(issues_summary, styles['Normal']))
            story.append(Spacer(1, 0.3 * inch))
            
            # Critical issues
            issues = analysis_data.get('issues', [])
            critical_issues = [i for i in issues if i.get('severity') == 'critical']
            
            if critical_issues:
                story.append(Paragraph("Critical Issues", styles['Heading2']))
                for idx, issue in enumerate(critical_issues, 1):
                    issue_text = f"""
                    <b>{idx}. {issue.get('message', 'N/A')}</b><br/>
                    <b>File:</b> {issue.get('file', 'N/A')} (Line {issue.get('line', 'N/A')})<br/>
                    <b>Suggestion:</b> {issue.get('suggestion', 'No suggestion')}
                    """
                    story.append(Paragraph(issue_text, styles['Normal']))
                    story.append(Spacer(1, 0.2 * inch))
            
            # Build PDF
            doc.build(story)
            
            logger.info(f"✅ PDF report generated: {filepath}")
            return filepath
            
        except Exception as e:
            logger.error(f"❌ Failed to generate PDF report: {e}")
            raise

# Global instance
report_service = ReportService()